import { chromium } from "playwright-core";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await b.newPage();
await p.goto("http://localhost:3220/tiktok-demo/authorization", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /تصريح لمحل ترند|Authorize Trend Store/ }).click();
await p.waitForURL("**/tiktok-demo/success", { timeout: 15000 });
await p.goto("http://localhost:3220/tiktok-bot/demo-account/comments", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /^حذف$|^Delete$/ }).first().click();
await p.getByRole("dialog").getByRole("button", { name: /^حذف$|^Delete$/ }).click();
await p.waitForTimeout(900);
const afterDelete = await p.locator("article").count();
await p.getByRole("button", { name: /إعادة ضبط|Reset Demo/ }).click();
await p.waitForURL("**/tiktok", { timeout: 15000 });
const disconnected = (await p.getByText(/غير متصل|Not connected/).count()) > 0;
await p.goto("http://localhost:3220/tiktok-demo/authorization", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /تصريح لمحل ترند|Authorize Trend Store/ }).click();
await p.waitForURL("**/tiktok-demo/success", { timeout: 15000 });
await p.goto("http://localhost:3220/tiktok-bot/demo-account/comments", { waitUntil: "networkidle" });
const afterReset = await p.locator("article").count();
console.log(`comments after delete: ${afterDelete}`);
console.log(`account disconnected by reset: ${disconnected}`);
console.log(`comments restored after reset: ${afterReset}`);
console.log(afterReset === 8 && disconnected ? "PASS reset demo restores state" : "FAIL reset demo");
await b.close();
